"""Generate the self-contained Chapter 6 notebooks.

The notebooks intentionally duplicate their setup cells so a reader can open any
one of them and run it top-to-bottom. Keeping those cells in this generator makes
the duplicated code reviewable and prevents optimizer examples from drifting.
"""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent


CHAPTER_DIR = Path(__file__).resolve().parent


def source(text: str) -> list[str]:
    return dedent(text).strip("\n").splitlines(keepends=True)


def markdown(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": source(text)}


def code(text: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source(text),
    }


def notebook(cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


INSTALL = code(
    """
    %pip install -r ../requirements.txt -q
    """
)


COMMON_SETUP = code(
    r'''
    import os
    import random
    from pathlib import Path

    import dspy
    import pandas as pd
    from dotenv import load_dotenv

    # Resolve paths whether Jupyter starts in the repo root or chapter06/.
    cwd = Path.cwd().resolve()
    REPO_ROOT = cwd if (cwd / "data" / "ai_vs_human200.csv").exists() else cwd.parent
    DATA_PATH = REPO_ROOT / "data" / "ai_vs_human200.csv"
    if not DATA_PATH.exists():
        raise FileNotFoundError("Start Jupyter in the repo root or chapter06 directory.")

    load_dotenv(REPO_ROOT / ".env")
    if not os.getenv("OPENAI_API_KEY"):
        raise EnvironmentError("Set OPENAI_API_KEY in the repo's .env file before running this notebook.")

    # Chapter 6 defaults: Luna for high-volume task calls, Sol for reflection.
    # Override either slug without editing the notebook.
    TASK_MODEL = os.getenv("TASK_MODEL", "openai/gpt-5.6-luna")
    REFLECTION_MODEL = os.getenv("REFLECTION_MODEL", "openai/gpt-5.6-sol")
    NUM_THREADS = int(os.getenv("DSPY_NUM_THREADS", "4"))
    TRAIN_LIMIT = int(os.getenv("TRAIN_LIMIT", "32"))
    VAL_LIMIT = int(os.getenv("VAL_LIMIT", "12"))
    EVAL_LIMIT = int(os.getenv("EVAL_LIMIT", "12"))

    # DSPy 3.2 treats GPT-5-family models as reasoning models and rejects small
    # max_tokens caps. Leave the provider default in place rather than setting an
    # invalid value below 16,000.
    task_lm = dspy.LM(TASK_MODEL)
    reflection_lm = dspy.LM(REFLECTION_MODEL)
    dspy.configure(lm=task_lm)

    print(f"DSPy {dspy.__version__}")
    print(f"Task model: {TASK_MODEL}")
    print(f"Reflection model: {REFLECTION_MODEL}")
    '''
)


LOCAL_SETUP = code(
    r'''
    import os
    import random
    from pathlib import Path

    import dspy
    import pandas as pd
    from dotenv import load_dotenv

    cwd = Path.cwd().resolve()
    REPO_ROOT = cwd if (cwd / "data" / "ai_vs_human200.csv").exists() else cwd.parent
    DATA_PATH = REPO_ROOT / "data" / "ai_vs_human200.csv"
    if not DATA_PATH.exists():
        raise FileNotFoundError("Start Jupyter in the repo root or chapter06 directory.")

    load_dotenv(REPO_ROOT / ".env")
    NUM_THREADS = int(os.getenv("DSPY_NUM_THREADS", "4"))
    TRAIN_LIMIT = int(os.getenv("TRAIN_LIMIT", "32"))
    VAL_LIMIT = int(os.getenv("VAL_LIMIT", "12"))
    EVAL_LIMIT = int(os.getenv("EVAL_LIMIT", "12"))
    print(f"DSPy {dspy.__version__}; local-model workflow")
    '''
)


COMMON_PROGRAM = code(
    r'''
    class DetectAIText(dspy.Signature):
        """Decide whether the supplied passage was generated by an AI."""

        text: str = dspy.InputField(desc="Passage to classify")
        is_ai: bool = dspy.OutputField(desc="True for AI-generated text; otherwise False")


    class AIDetector(dspy.Module):
        def __init__(self):
            super().__init__()
            self.detect = dspy.ChainOfThought(DetectAIText)

        def forward(self, text: str):
            return self.detect(text=text)


    def as_bool(value) -> bool:
        if isinstance(value, bool):
            return value
        normalized = str(value).strip().lower()
        if normalized in {"true", "1", "yes"}:
            return True
        if normalized in {"false", "0", "no"}:
            return False
        raise ValueError(f"Cannot interpret {value!r} as a boolean")


    def exact_match(example, prediction, trace=None) -> float:
        return float(as_bool(prediction.is_ai) == bool(example.is_ai))


    def feedback_metric(example, prediction, trace=None, **kwargs):
        score = exact_match(example, prediction)
        feedback = (
            "The classification is correct. Preserve the reasoning cues that led to it."
            if score
            else f"The classification is incorrect. The expected is_ai value is {bool(example.is_ai)}. "
                 "Focus on concrete stylistic evidence instead of topic or polish alone."
        )
        return dspy.Prediction(score=score, feedback=feedback)


    frame = pd.read_csv(DATA_PATH)
    examples = [
        dspy.Example(text=row.text, is_ai=bool(row.is_ai)).with_inputs("text")
        for row in frame.itertuples(index=False)
    ]
    random.Random(42).shuffle(examples)

    # Deterministic 50/25/25 split; environment variables keep default runs inexpensive.
    train_end = len(examples) // 2
    val_end = train_end + len(examples) // 4
    full_trainset, full_valset, full_testset = (
        examples[:train_end], examples[train_end:val_end], examples[val_end:]
    )
    trainset = full_trainset[:TRAIN_LIMIT] if TRAIN_LIMIT else full_trainset
    valset = full_valset[:VAL_LIMIT] if VAL_LIMIT else full_valset
    testset = full_testset[:EVAL_LIMIT] if EVAL_LIMIT else full_testset

    def evaluate(program, dataset=testset):
        runner = dspy.Evaluate(
            devset=dataset,
            metric=exact_match,
            num_threads=NUM_THREADS,
            max_errors=max(1, len(dataset)),
            provide_traceback=True,
            failure_score=0.0,
            display_progress=True,
            display_table=5,
        )
        result = runner(program)
        failed = [index for index, (_, prediction, _) in enumerate(result.results) if not hasattr(prediction, "is_ai")]
        if failed:
            raise RuntimeError(f"Evaluation failed for example indexes {failed}; inspect the tracebacks above.")
        return result.score


    detector = AIDetector()
    print(f"train={len(trainset)}, validation={len(valset)}, test={len(testset)}")
    '''
)


BASELINE = code(
    """
    baseline_score = evaluate(detector)
    print(f"Baseline score: {baseline_score}")
    """
)


RESULT = code(
    """
    optimized_score = evaluate(optimized_detector)
    print(f"Optimized score: {optimized_score}")
    print(f"Delta: {optimized_score - baseline_score:+.2f}")

    example = testset[0]
    prediction = optimized_detector(**example.inputs())
    print({"expected": example.is_ai, "predicted": prediction.is_ai})
    """
)


def optimizer_notebook(
    title: str,
    description: str,
    optimizer_code: str,
    *,
    extra_cells: list[dict] | None = None,
    install: dict = INSTALL,
    result: dict = RESULT,
) -> dict:
    cells = [
        markdown(
            f"""
            # {title}

            {description}

            This notebook is self-contained and targets the stable DSPy 3.x API pinned by
            `requirements.txt`. Its default data and optimizer budgets are smoke-test sized;
            set `TRAIN_LIMIT=0`, `VAL_LIMIT=0`, and `EVAL_LIMIT=0` for the complete split.
            """
        ),
        install,
        COMMON_SETUP,
        COMMON_PROGRAM,
        BASELINE,
    ]
    if extra_cells:
        cells.extend(extra_cells)
    cells.extend([code(optimizer_code), result])
    return notebook(cells)


NOTEBOOKS: dict[str, dict] = {}


NOTEBOOKS["labeled-few-shot.ipynb"] = optimizer_notebook(
    "LabeledFewShot",
    "Samples labeled demonstrations without asking a teacher model to synthesize traces.",
    """
    optimizer = dspy.LabeledFewShot(k=4)
    optimized_detector = optimizer.compile(detector, trainset=trainset, sample=True)
    """,
)


NOTEBOOKS["bootstrap-few-shot.ipynb"] = optimizer_notebook(
    "BootstrapFewShot",
    "Bootstraps successful reasoning traces, then attaches them as demonstrations.",
    """
    optimizer = dspy.BootstrapFewShot(
        metric=exact_match,
        max_bootstrapped_demos=2,
        max_labeled_demos=2,
        max_rounds=1,
    )
    optimized_detector = optimizer.compile(detector, trainset=trainset)
    """,
)


NOTEBOOKS["bootstrap-random-search.ipynb"] = optimizer_notebook(
    "BootstrapFewShotWithRandomSearch",
    "Searches over several bootstrapped demonstration sets and selects on validation data.",
    """
    optimizer = dspy.BootstrapFewShotWithRandomSearch(
        metric=exact_match,
        max_bootstrapped_demos=2,
        max_labeled_demos=2,
        max_rounds=1,
        num_candidate_programs=4,
        num_threads=NUM_THREADS,
        max_errors=1,
    )
    optimized_detector = optimizer.compile(
        detector,
        trainset=trainset,
        valset=valset,
    )
    """,
)


NOTEBOOKS["bootstrap-optuna.ipynb"] = optimizer_notebook(
    "BootstrapFewShotWithOptuna",
    "Uses Optuna to select a strong combination of bootstrapped demonstrations.",
    """
    optimizer = dspy.BootstrapFewShotWithOptuna(
        metric=exact_match,
        max_bootstrapped_demos=2,
        max_labeled_demos=2,
        max_rounds=1,
        num_candidate_programs=4,
        num_threads=NUM_THREADS,
    )
    optimized_detector = optimizer.compile(
        detector,
        max_demos=4,
        trainset=trainset,
        valset=valset,
    )
    """,
    install=code(
        """
        %pip install -r ../requirements.txt -q optuna
        """
    ),
)


KNN_INSTALL = code(
    """
    %pip install -r ../requirements.txt -q sentence-transformers
    """
)


KNN_RESULT = code(
    r'''
    # KNNFewShot retrieves and bootstraps examples dynamically for every input. A
    # serial loop keeps any single failure visible instead of ending with the opaque
    # "Execution cancelled" message produced by a parallel batch.
    correct = 0
    failures = []
    for index, example in enumerate(testset):
        try:
            prediction = optimized_detector(**example.inputs())
            correct += int(exact_match(example, prediction))
        except Exception as exc:
            failures.append((index, type(exc).__name__, str(exc)))

    if failures:
        raise RuntimeError(f"KNN evaluation failures (first shown): {failures[0]}")

    optimized_score = 100.0 * correct / len(testset)
    print(f"KNNFewShot score: {optimized_score:.2f}")
    print(f"Baseline score: {baseline_score}")
    '''
)


NOTEBOOKS["knn-few-shot.ipynb"] = optimizer_notebook(
    "KNNFewShot",
    "Retrieves the nearest labeled examples for each input, then builds a few-shot program on demand.",
    r'''
    from sentence_transformers import SentenceTransformer

    embedding_model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    vectorizer = dspy.Embedder(embedding_model.encode)

    # DSPy 3.x API contract:
    # - k, trainset, and vectorizer are constructor arguments.
    # - BootstrapFewShot arguments may also be supplied here.
    # - num_threads is NOT accepted: it would be forwarded to BootstrapFewShot and fail.
    # - compile() receives the student, not trainset or valset.
    optimizer = dspy.KNNFewShot(
        k=4,
        trainset=trainset,
        vectorizer=vectorizer,
        metric=exact_match,
        max_bootstrapped_demos=2,
        max_labeled_demos=0,
        max_rounds=1,
    )
    optimized_detector = optimizer.compile(detector)
    ''',
    install=KNN_INSTALL,
    result=KNN_RESULT,
)


NOTEBOOKS["infer-rules.ipynb"] = optimizer_notebook(
    "InferRules",
    "Infers reusable natural-language rules from labeled examples.",
    """
    optimizer = dspy.InferRules(
        num_candidates=3,
        num_rules=3,
        num_threads=NUM_THREADS,
        teacher_settings={"lm": reflection_lm},
    )
    optimized_detector = optimizer.compile(
        detector,
        trainset=trainset,
        valset=valset,
    )
    """,
)


NOTEBOOKS["copro.ipynb"] = optimizer_notebook(
    "COPRO",
    "Iteratively proposes and scores instruction variants; Sol handles proposal generation.",
    """
    optimizer = dspy.COPRO(
        prompt_model=reflection_lm,
        metric=exact_match,
        breadth=3,
        depth=1,
        init_temperature=1.0,
    )
    optimized_detector = optimizer.compile(
        detector,
        trainset=trainset,
        eval_kwargs={
            "num_threads": NUM_THREADS,
            "display_progress": True,
            "display_table": 0,
        },
    )
    """,
)


NOTEBOOKS["miprov2.ipynb"] = optimizer_notebook(
    "MIPROv2",
    "Jointly searches instructions and demonstrations; Luna executes the task and Sol proposes prompts.",
    """
    optimizer = dspy.MIPROv2(
        metric=exact_match,
        prompt_model=reflection_lm,
        task_model=task_lm,
        auto="light",
        max_bootstrapped_demos=2,
        max_labeled_demos=2,
        num_threads=NUM_THREADS,
        seed=42,
    )
    optimized_detector = optimizer.compile(
        detector,
        trainset=trainset,
        valset=valset,
        minibatch=True,
        minibatch_size=min(12, len(valset)),
        requires_permission_to_run=False,
    )
    """,
)


NOTEBOOKS["gepa.ipynb"] = optimizer_notebook(
    "GEPA",
    "Uses textual metric feedback and a reflection model to evolve program instructions.",
    """
    use_word_limit = os.getenv("USE_WORD_LIMIT_PROPOSER", "0") == "1"
    optimizer = dspy.GEPA(
        metric=feedback_metric,
        max_full_evals=2,
        reflection_minibatch_size=3,
        reflection_lm=reflection_lm,
        instruction_proposer=WordLimitProposer(max_words=50) if use_word_limit else None,
        num_threads=NUM_THREADS,
        use_merge=False,
        track_stats=True,
        seed=42,
    )
    optimized_detector = optimizer.compile(
        detector,
        trainset=trainset,
        valset=valset,
    )
    """,
    extra_cells=[
        code(
            r'''
            from gepa.core.adapter import ProposalFn


            class GenerateWordLimitedInstruction(dspy.Signature):
                """Improve an instruction from feedback while respecting a word limit."""

                current_instruction: str = dspy.InputField()
                feedback_summary: str = dspy.InputField()
                max_words: int = dspy.InputField()
                improved_instruction: str = dspy.OutputField()


            class WordLimitProposer(ProposalFn):
                """Optional GEPA proposer corresponding to the chapter's custom-proposer block."""

                def __init__(self, max_words: int = 50):
                    self.max_words = max_words
                    self.improver = dspy.ChainOfThought(GenerateWordLimitedInstruction)
                    self.improver.set_lm(reflection_lm)

                def __call__(self, candidate, reflective_dataset, components_to_update):
                    updated = {}
                    for name in components_to_update:
                        if name not in candidate or name not in reflective_dataset:
                            continue
                        feedback = "\n".join(
                            f"Example {index + 1}: {example.get('Feedback', '')}"
                            for index, example in enumerate(reflective_dataset[name])
                        )
                        proposal = self.improver(
                            current_instruction=candidate[name],
                            feedback_summary=feedback,
                            max_words=self.max_words,
                        ).improved_instruction
                        updated[name] = " ".join(str(proposal).split()[: self.max_words])
                    return updated


            print("Set USE_WORD_LIMIT_PROPOSER=1 to run GEPA with the 50-word custom proposer.")
            ''',
        )
    ],
)


NOTEBOOKS["simba.ipynb"] = optimizer_notebook(
    "SIMBA",
    "Samples trajectories, finds high-variance examples, and adds reflective rules or demonstrations.",
    """
    optimizer = dspy.SIMBA(
        metric=exact_match,
        bsize=min(8, len(trainset)),
        num_candidates=2,
        max_steps=2,
        max_demos=2,
        prompt_model=reflection_lm,
        num_threads=NUM_THREADS,
    )
    optimized_detector = optimizer.compile(detector, trainset=trainset, seed=42)
    """,
)


NOTEBOOKS["ensemble.ipynb"] = optimizer_notebook(
    "Ensemble",
    "Compiles several independently optimized programs, then randomly samples voters at inference time.",
    """
    labeled = dspy.LabeledFewShot(k=4).compile(detector.deepcopy(), trainset=trainset)

    bootstrapped = dspy.BootstrapFewShot(
        metric=exact_match,
        max_bootstrapped_demos=2,
        max_labeled_demos=2,
        max_rounds=1,
    ).compile(detector.deepcopy(), trainset=trainset)

    searched = dspy.BootstrapFewShotWithRandomSearch(
        metric=exact_match,
        max_bootstrapped_demos=2,
        max_labeled_demos=2,
        max_rounds=1,
        num_candidate_programs=3,
        num_threads=NUM_THREADS,
        max_errors=1,
    ).compile(detector.deepcopy(), trainset=trainset, valset=valset)

    optimizer = dspy.Ensemble(reduce_fn=dspy.majority, size=3)
    optimized_detector = optimizer.compile([labeled, bootstrapped, searched])
    """,
)


FINETUNE_INSTALL = code(
    """
    %pip install -r ../requirements.txt -q torch transformers datasets accelerate peft trl "sglang[all]"
    """
)


NOTEBOOKS["bootstrap-finetune.ipynb"] = notebook(
    [
        markdown(
            """
            # BootstrapFinetune (CUDA)

            `BootstrapFinetune` trains model weights from successful DSPy traces. GPT-5.6
            Luna and Sol do not support fine-tuning, so this notebook uses Sol as the
            teacher and a local Qwen model as the trainable student. It requires an NVIDIA
            CUDA GPU and SGLang; the notebook fails early with a clear hardware message.
            """
        ),
        FINETUNE_INSTALL,
        COMMON_SETUP,
        COMMON_PROGRAM,
        code(
            r'''
            import torch
            from dspy.clients.lm_local import LocalProvider

            if not torch.cuda.is_available():
                raise RuntimeError("BootstrapFinetune requires an NVIDIA CUDA GPU. Use finetune-mac-m3.ipynb on Apple Silicon.")

            LOCAL_MODEL = os.getenv("LOCAL_MODEL", "Qwen/Qwen2.5-1.5B-Instruct")
            local_lm = dspy.LM(
                f"openai/local:{LOCAL_MODEL}",
                provider=LocalProvider(),
                max_tokens=512,
            )

            student = AIDetector()
            student.set_lm(local_lm)
            teacher = AIDetector()
            teacher.set_lm(reflection_lm)

            optimizer = dspy.BootstrapFinetune(
                metric=exact_match,
                multitask=False,
                train_kwargs={
                    "num_train_epochs": 1,
                    "per_device_train_batch_size": 1,
                    "gradient_accumulation_steps": 4,
                    "learning_rate": 2e-5,
                    "max_seq_length": 1_024,
                    "device": "cuda",
                    "use_peft": True,
                },
            )

            # teacher is a DSPy Module, not an LM. Each student predictor already has local_lm assigned.
            optimized_detector = optimizer.compile(
                student,
                trainset=trainset,
                teacher=teacher,
            )
            ''',
        ),
        code(
            """
            # BootstrapFinetune returns the trained model but does not launch its
            # local inference server. Launch once for evaluation, then clean up.
            optimized_lms = {predictor.lm for predictor in optimized_detector.predictors()}
            for lm in optimized_lms:
                lm.launch()
            try:
                optimized_score = evaluate(optimized_detector)
                print(f"Fine-tuned score: {optimized_score}")
            finally:
                for lm in optimized_lms:
                    lm.kill()
            """
        ),
    ]
)


NOTEBOOKS["better-together.ipynb"] = notebook(
    [
        markdown(
            """
            # BetterTogether (CUDA)

            `BetterTogether` alternates prompt optimization (`p`) and weight optimization
            (`w`). The keyword names passed to the constructor define the strategy symbols;
            this notebook therefore uses `p=...`, `w=...` and `strategy="p -> w -> p"`.
            It requires the same CUDA/SGLang stack as `BootstrapFinetune`.
            """
        ),
        FINETUNE_INSTALL,
        COMMON_SETUP,
        COMMON_PROGRAM,
        code(
            r'''
            import torch
            from dspy.clients.lm_local import LocalProvider

            if not torch.cuda.is_available():
                raise RuntimeError("BetterTogether weight optimization requires an NVIDIA CUDA GPU.")

            LOCAL_MODEL = os.getenv("LOCAL_MODEL", "Qwen/Qwen2.5-1.5B-Instruct")
            local_lm = dspy.LM(
                f"openai/local:{LOCAL_MODEL}",
                provider=LocalProvider(),
                max_tokens=512,
            )
            student = AIDetector()
            student.set_lm(local_lm)

            prompt_optimizer = dspy.MIPROv2(
                metric=exact_match,
                prompt_model=reflection_lm,
                task_model=local_lm,
                auto="light",
                max_bootstrapped_demos=2,
                max_labeled_demos=2,
                num_threads=NUM_THREADS,
            )
            weight_optimizer = dspy.BootstrapFinetune(
                metric=exact_match,
                multitask=False,
                train_kwargs={
                    "num_train_epochs": 1,
                    "per_device_train_batch_size": 1,
                    "gradient_accumulation_steps": 4,
                    "max_seq_length": 1_024,
                    "device": "cuda",
                    "use_peft": True,
                },
            )

            optimizer = dspy.BetterTogether(
                metric=exact_match,
                p=prompt_optimizer,
                w=weight_optimizer,
            )
            optimized_detector = optimizer.compile(
                student,
                trainset=trainset,
                valset=valset,
                strategy="p -> w -> p",
            )
            ''',
        ),
        code(
            """
            # BetterTogether cleans up local servers before returning.
            optimized_lms = {predictor.lm for predictor in optimized_detector.predictors()}
            for lm in optimized_lms:
                lm.launch()
            try:
                optimized_score = evaluate(optimized_detector)
                print(f"BetterTogether score: {optimized_score}")
            finally:
                for lm in optimized_lms:
                    lm.kill()
            """
        ),
    ]
)


GRPO_INSTALL = code(
    """
    %pip install -r ../requirements.txt -q arbor-ai
    """
)


NOTEBOOKS["grpo.ipynb"] = notebook(
    [
        markdown(
            """
            # GRPO with Arbor (experimental, multi-GPU)

            This follows DSPy's current Arbor integration rather than the removed
            `dspy.clients.lm_local_arbor` import. It requires Linux and multiple NVIDIA
            GPUs. Arbor may require a newer DSPy prerelease than the chapter's stable
            `3.2.1` pin; check Arbor's compatibility notes before a long run.
            """
        ),
        GRPO_INSTALL,
        LOCAL_SETUP,
        COMMON_PROGRAM,
        code(
            r'''
            import torch

            if not torch.cuda.is_available() or torch.cuda.device_count() < 2:
                raise RuntimeError("The Arbor GRPO example requires at least two NVIDIA GPUs.")

            import arbor
            from arbor import ArborGRPO, ArborProvider

            LOCAL_MODEL = os.getenv("LOCAL_MODEL", "Qwen/Qwen2.5-1.5B-Instruct")
            server = arbor.init()
            local_lm = dspy.LM(
                f"openai/arbor:{LOCAL_MODEL}",
                provider=ArborProvider(),
                api_base=server["base_url"],
                max_tokens=512,
                temperature=1.0,
                top_p=1.0,
                top_k=-1,
                repetition_penalty=1.0,
            )
            student = AIDetector()
            student.set_lm(local_lm)

            def reward(example, prediction, trace=None):
                return exact_match(example, prediction)

            optimizer = ArborGRPO(
                metric=reward,
                train_kwargs={
                    "num_training_gpus": max(1, torch.cuda.device_count() - 1),
                    "num_inference_gpus": 1,
                    "num_train_epochs": 1,
                    "learning_rate": 1e-6,
                },
                checkpoint="single-best",
            )
            optimized_detector = optimizer.compile(student, trainset=trainset)
            ''',
        ),
        code(
            """
            optimized_score = evaluate(optimized_detector)
            print(f"GRPO score: {optimized_score}")
            """
        ),
    ]
)


NOTEBOOKS["finetune-mac-m3.ipynb"] = notebook(
    [
        markdown(
            """
            # Manual LoRA fine-tuning on Apple Silicon

            DSPy's weight optimizers target CUDA-first providers. This self-contained
            alternative exports the same classification task to Transformers/PEFT and
            trains a small local model with MPS. It is a platform appendix, not a DSPy
            optimizer API example.
            """
        ),
        code(
            """
            %pip install -r ../requirements.txt -q torch transformers datasets accelerate peft trl
            """
        ),
        LOCAL_SETUP,
        COMMON_PROGRAM,
        code(
            r'''
            import torch
            from datasets import Dataset
            from peft import LoraConfig
            from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
            from trl import SFTConfig, SFTTrainer

            if not torch.backends.mps.is_available():
                raise RuntimeError("This notebook requires Apple Silicon with PyTorch MPS support.")

            LOCAL_MODEL = os.getenv("LOCAL_MODEL", "Qwen/Qwen2.5-0.5B-Instruct")
            tokenizer = AutoTokenizer.from_pretrained(LOCAL_MODEL)
            tokenizer.pad_token = tokenizer.pad_token or tokenizer.eos_token
            model = AutoModelForCausalLM.from_pretrained(
                LOCAL_MODEL,
                torch_dtype=torch.float16,
                device_map={"": "mps"},
            )

            def training_text(example):
                label = "true" if example.is_ai else "false"
                return (
                    "Classify whether the passage was AI generated. Reply only true or false.\n"
                    f"Passage: {example.text}\nAnswer: {label}"
                )

            dataset = Dataset.from_dict({"text": [training_text(ex) for ex in trainset]})
            peft_config = LoraConfig(
                r=8,
                lora_alpha=16,
                lora_dropout=0.05,
                bias="none",
                task_type="CAUSAL_LM",
                target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
            )
            config = SFTConfig(
                output_dir=str(REPO_ROOT / "chapter06" / "runs" / "qwen-ai-detector-mps"),
                dataset_text_field="text",
                max_length=512,
                num_train_epochs=1,
                per_device_train_batch_size=1,
                gradient_accumulation_steps=4,
                learning_rate=2e-4,
                logging_steps=5,
                report_to="none",
                use_mps_device=True,
            )
            trainer = SFTTrainer(
                model=model,
                args=config,
                train_dataset=dataset,
                processing_class=tokenizer,
                peft_config=peft_config,
            )
            trainer.train()
            ''',
        ),
    ]
)


NOTEBOOKS["quickstart-ai-detector.ipynb"] = notebook(
    [
        markdown(
            """
            # Chapter 6 quickstart: AI-text detector

            This is the unoptimized baseline shared by the optimizer notebooks. Luna is
            the inexpensive task model; the Sol reflection model is initialized for the
            optimizer notebooks but is not called here.
            """
        ),
        INSTALL,
        COMMON_SETUP,
        COMMON_PROGRAM,
        BASELINE,
        code(
            """
            example = testset[0]
            prediction = detector(**example.inputs())
            print({"text": example.text, "expected": example.is_ai, "predicted": prediction.is_ai})
            """
        ),
    ]
)


NOTEBOOKS["optimizer-benchmark.ipynb"] = notebook(
    [
        markdown(
            """
            # Chapter 6 optimizer notebook index

            The former all-in-one benchmark made one optimizer failure cancel an entire
            expensive run. Chapter 6 now keeps every optimizer in a self-contained
            notebook so each API, dependency set, budget, and result can be tested alone.

            | Optimizer | Notebook | Notes |
            |---|---|---|
            | LabeledFewShot | `labeled-few-shot.ipynb` | no synthesized traces |
            | BootstrapFewShot | `bootstrap-few-shot.ipynb` | bootstrapped traces |
            | Random search | `bootstrap-random-search.ipynb` | candidate demo sets |
            | Optuna | `bootstrap-optuna.ipynb` | Optuna selection |
            | KNNFewShot | `knn-few-shot.ipynb` | dynamic retrieval; special compile API |
            | InferRules | `infer-rules.ipynb` | inferred natural-language rules |
            | COPRO | `copro.ipynb` | instruction search |
            | MIPROv2 | `miprov2.ipynb` | instruction + demo search |
            | GEPA | `gepa.ipynb` | reflective textual feedback |
            | SIMBA | `simba.ipynb` | stochastic introspection |
            | Ensemble | `ensemble.ipynb` | combines optimized programs |
            | BootstrapFinetune | `bootstrap-finetune.ipynb` | CUDA/SGLang |
            | BetterTogether | `better-together.ipynb` | prompt + weight optimization |
            | GRPO | `grpo.ipynb` | experimental Arbor multi-GPU path |

            Run `quickstart-ai-detector.ipynb` for the common baseline. Historical scores
            in the chapter were produced with older models and should not be compared
            directly with GPT-5.6 Luna/Sol runs.
            """
        ),
        INSTALL,
        code(
            """
            import dspy
            print(f"DSPy version: {dspy.__version__}")
            assert tuple(map(int, dspy.__version__.split(".")[:2])) >= (3, 2)
            print("Open one optimizer notebook above and run it top-to-bottom.")
            """
        ),
    ]
)


def main() -> None:
    for filename, data in NOTEBOOKS.items():
        path = CHAPTER_DIR / filename
        path.write_text(json.dumps(data, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"wrote {path.relative_to(CHAPTER_DIR.parent)}")


if __name__ == "__main__":
    main()
