"""Shared executable runtime for the Chapter 6 optimizer notebooks.

Every notebook loads the same frozen, pair-grouped dataset through this module.
Prompt optimizers use Luna/Sol; weight optimizers train Qwen locally through DSPy
and the Apple Silicon provider in :mod:`chapter06.apple_finetune`.
"""

from __future__ import annotations

import csv
import hashlib
import json
import os
import re
import tempfile
import time
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

import dspy
import numpy as np
from dotenv import load_dotenv

from chapter06.experiments.gepa_expanded.guardrails import summarize_history


REPO_ROOT = Path(__file__).resolve().parents[1]
CHAPTER_DIR = REPO_ROOT / "chapter06"
DATA_PATH = REPO_ROOT / "data" / "ai_vs_human_chapter06_expanded.csv"
SPLIT_PATH = REPO_ROOT / "data" / "ai_vs_human_chapter06_expanded_splits.json"
RESULTS_ROOT = CHAPTER_DIR / "results" / "expanded_notebooks"
SUMMARY_PATH = RESULTS_ROOT / "comparison.json"

PROMPT_OPTIMIZERS = {
    "quickstart",
    "labeled-few-shot",
    "bootstrap-few-shot",
    "bootstrap-random-search",
    "knn-few-shot",
    "copro",
    "miprov2",
    "gepa",
    "simba",
    "ensemble",
}
WEIGHT_OPTIMIZERS = {"bootstrap-finetune", "better-together"}
OPTIMIZERS = PROMPT_OPTIMIZERS | WEIGHT_OPTIMIZERS


class DetectAIText(dspy.Signature):
    """Decide whether the supplied passage was generated by an AI."""

    text: str = dspy.InputField(desc="Passage to classify")
    is_ai: bool = dspy.OutputField(desc="True for AI-generated text; otherwise False")


class AIDetector(dspy.Module):
    def __init__(self) -> None:
        super().__init__()
        self.detect = dspy.ChainOfThought(DetectAIText)

    def forward(self, text: str):
        return self.detect(text=text)


def as_bool(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    normalized = str(value).strip().lower()
    if normalized in {"true", "1", "yes"}:
        return True
    if normalized in {"false", "0", "no"}:
        return False
    raise ValueError(f"cannot interpret {value!r} as a boolean")


def exact_match(example: dspy.Example, prediction: Any, trace: Any = None) -> float:
    del trace
    return float(as_bool(prediction.is_ai) == bool(example.is_ai))


def feedback_metric(
    example: dspy.Example,
    prediction: Any,
    trace: Any = None,
    pred_name: str | None = None,
    pred_trace: Any = None,
):
    del trace, pred_name, pred_trace
    score = exact_match(example, prediction)
    feedback = (
        "Correct. Preserve the concrete stylistic evidence supporting this decision."
        if score
        else (
            f"Incorrect: the provenance label is is_ai={bool(example.is_ai)}. "
            "Judge writing style rather than topic or technical sophistication."
        )
    )
    return dspy.Prediction(score=score, feedback=feedback)


def load_frozen_examples() -> dict[str, list[dspy.Example]]:
    """Load and validate the one frozen dataset/split used by every notebook."""

    manifest = json.loads(SPLIT_PATH.read_text(encoding="utf-8"))
    observed_hash = hashlib.sha256(DATA_PATH.read_bytes()).hexdigest()
    if observed_hash != manifest["dataset_sha256"]:
        raise ValueError("Chapter 6 dataset hash no longer matches the frozen manifest")
    with DATA_PATH.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))
    if len(rows) != manifest["row_count"]:
        raise ValueError("Chapter 6 row count no longer matches the frozen manifest")
    by_pair: dict[str, list[dict[str, str]]] = {}
    for row in rows:
        by_pair.setdefault(row["pair_id"], []).append(row)

    result: dict[str, list[dspy.Example]] = {}
    seen: set[str] = set()
    for split_name, pair_ids in manifest["splits"].items():
        examples: list[dspy.Example] = []
        for pair_id in pair_ids:
            if pair_id in seen:
                raise ValueError(f"pair {pair_id!r} appears in multiple splits")
            seen.add(pair_id)
            pair = by_pair.get(pair_id, [])
            if len(pair) != 2:
                raise ValueError(f"pair {pair_id!r} must contain one human and one AI row")
            for row in pair:
                examples.append(
                    dspy.Example(
                        pair_id=row["pair_id"],
                        example_id=row["example_id"],
                        text=row["text"],
                        is_ai=as_bool(row["is_ai"]),
                    ).with_inputs("text")
                )
        result[split_name] = examples
    if seen != set(by_pair):
        raise ValueError("the split manifest does not cover every Chapter 6 pair")
    return result


def split_summary(splits: dict[str, Sequence[dspy.Example]]) -> str:
    parts = []
    for name in ("train", "validation", "test"):
        examples = splits[name]
        labels = Counter(bool(example.is_ai) for example in examples)
        parts.append(
            f"{name}={len(examples)} (human={labels[False]}, AI={labels[True]})"
        )
    return "; ".join(parts)


def accepted_trace_label_counts(trace_data: Sequence[dict[str, Any]]) -> dict[str, int]:
    """Count labels in metric-accepted DSPy traces before SFT formatting."""

    counts: Counter[bool] = Counter()
    for item in trace_data:
        if not item.get("score"):
            continue
        prediction = item.get("prediction")
        if prediction is None or not hasattr(prediction, "is_ai"):
            raise ValueError("an accepted BootstrapFinetune trace has no is_ai output")
        counts[as_bool(prediction.is_ai)] += 1
    return {"human": counts[False], "ai": counts[True], "total": sum(counts.values())}


class BalancedBootstrapFinetune(dspy.BootstrapFinetune):
    """BootstrapFinetune with a guard against one-class accepted trace sets."""

    def __init__(self, *args: Any, min_examples_per_class: int = 2, **kwargs: Any):
        super().__init__(*args, **kwargs)
        self.min_examples_per_class = min_examples_per_class
        self.accepted_label_counts: dict[str, int] = {}

    def _prepare_finetune_data(
        self,
        trace_data: list[dict[str, Any]],
        lm: dspy.LM,
        pred_ind: int | None = None,
    ):
        counts = accepted_trace_label_counts(trace_data)
        self.accepted_label_counts = counts
        if min(counts["human"], counts["ai"]) < self.min_examples_per_class:
            raise ValueError(
                "BootstrapFinetune rejected an imbalanced accepted-trace set: "
                f"human={counts['human']}, ai={counts['ai']}; require at least "
                f"{self.min_examples_per_class} of each class. Use a stronger teacher."
            )
        return super()._prepare_finetune_data(trace_data, lm, pred_ind)


def hashed_ngram_embeddings(
    texts: Sequence[str], *, dimensions: int = 512
) -> np.ndarray:
    matrix = np.zeros((len(texts), dimensions), dtype=np.float32)
    for row_index, text in enumerate(texts):
        tokens = re.findall(r"[A-Za-z0-9_]+", text.lower())
        features = tokens + [
            f"{left}::{right}" for left, right in zip(tokens, tokens[1:])
        ]
        for feature in features:
            digest = hashlib.sha256(feature.encode("utf-8")).digest()
            column = int.from_bytes(digest[:4], "big") % dimensions
            matrix[row_index, column] += 1.0 if digest[4] & 1 else -1.0
        norm = float(np.linalg.norm(matrix[row_index]))
        if norm:
            matrix[row_index] /= norm
    return matrix


def boolean_majority(predictions: list[Any]):
    return dspy.majority(
        predictions, field="is_ai", normalize=lambda value: str(value).lower()
    )


def evaluate(program: dspy.Module, examples: Sequence[dspy.Example]) -> dict[str, Any]:
    predictions: list[dict[str, Any]] = []
    latencies: list[float] = []
    for example in examples:
        started = time.monotonic()
        try:
            prediction = program(**example.inputs())
            predicted = as_bool(prediction.is_ai)
            status = "completed"
            error = None
        except Exception as exc:
            # A malformed local-model response is a model error and therefore
            # an incorrect prediction, not grounds to discard the run.
            predicted = None
            status = "parse_error"
            error = f"{type(exc).__name__}: {exc}"[:240]
        elapsed = time.monotonic() - started
        latencies.append(elapsed)
        row = {
            "pair_id": example.pair_id,
            "example_id": example.example_id,
            "expected_is_ai": bool(example.is_ai),
            "predicted_is_ai": predicted,
            "correct": status == "completed" and predicted == bool(example.is_ai),
            "latency_seconds": elapsed,
            "status": status,
        }
        if error:
            row["error"] = error
        predictions.append(row)
    correct = sum(item["correct"] for item in predictions)
    ordered = sorted(latencies)
    p95_index = min(len(ordered) - 1, int(0.95 * len(ordered)))
    return {
        "accuracy": 100 * correct / len(predictions),
        "correct": correct,
        "count": len(predictions),
        "mean_latency_seconds": sum(latencies) / len(latencies),
        "p95_latency_seconds": ordered[p95_index],
        "predictions": predictions,
    }


@dataclass
class OptimizerRun:
    optimizer: str
    task_model: str
    final: dict[str, Any] | None
    validation: dict[str, Any]
    program: dspy.Module
    optimization_seconds: float
    baseline: dict[str, Any] | None = None
    accepted_trace_labels: dict[str, int] | None = None
    output_dir: str | None = None
    mode: str = "full"
    optimization_cost_usd: float = 0.0
    evaluation_cost_usd: float = 0.0
    usage: dict[str, Any] | None = None

    def summary(self) -> dict[str, Any]:
        scored = self.final or self.validation
        result = {
            "optimizer": self.optimizer,
            "status": "completed",
            "mode": self.mode,
            "task_model": self.task_model,
            "final_accuracy": scored["accuracy"],
            "correct": scored["correct"],
            "test_examples": scored["count"],
            "validation_accuracy": self.validation["accuracy"],
            "validation_correct": self.validation["correct"],
            "validation_examples": self.validation["count"],
            "optimization_seconds": self.optimization_seconds,
            "optimization_cost_usd": self.optimization_cost_usd,
            "evaluation_cost_usd": self.evaluation_cost_usd,
            "mean_latency_seconds": scored["mean_latency_seconds"],
            "p95_latency_seconds": scored["p95_latency_seconds"],
            "accepted_trace_labels": self.accepted_trace_labels,
            "output_dir": self.output_dir,
        }
        if self.baseline is not None:
            result["baseline_accuracy"] = self.baseline["accuracy"]
            result["uplift_points"] = scored["accuracy"] - self.baseline["accuracy"]
        return result


def _combined_usage(*lms: Any) -> dict[str, Any]:
    histories: list[dict[str, Any]] = []
    seen: set[int] = set()
    for lm in lms:
        if lm is None or id(lm) in seen:
            continue
        seen.add(id(lm))
        histories.extend(getattr(lm, "history", []))
    return summarize_history(histories)


def published_result(optimizer: str) -> dict[str, Any]:
    summary = json.loads(SUMMARY_PATH.read_text(encoding="utf-8"))
    row = next(row for row in summary["rows"] if row["optimizer"] == optimizer)
    if row["status"] != "completed":
        return {
            "optimizer": optimizer,
            "status": row["status"],
            "reason": row.get("reason", "No completed expanded-dataset run is available."),
        }
    accuracy = row["locked_test_accuracy_pct"]
    test_examples = row["locked_test_rows"]
    result = {
        "optimizer": optimizer,
        "status": "completed",
        "task_model": row["task_model"],
        "final_accuracy": accuracy,
        "correct": row["locked_test_correct"],
        "test_examples": test_examples,
        "baseline_accuracy": row.get("baseline_accuracy_pct"),
        "uplift_points": row.get("absolute_uplift_pct_points"),
        "validation_accuracy": row.get("optimized_validation_accuracy_pct"),
        "optimization_cost_usd": row.get("optimization_cost_usd"),
        "optimization_seconds": row["optimization_time_seconds"],
        "mean_latency_seconds": row["mean_inference_latency_seconds"],
        "p95_latency_seconds": row["p95_inference_latency_seconds"],
    }
    if row.get("accepted_trace_labels"):
        result["accepted_trace_labels"] = row["accepted_trace_labels"]
    return result


def format_result(result: dict[str, Any]) -> str:
    if result.get("status") and result["status"] != "completed":
        return (
            f"optimizer: {result['optimizer']}\n"
            f"status: {result['status']}\n"
            f"reason: {result['reason']}"
        )
    lines = [
        f"optimizer: {result['optimizer']}",
        f"task model: {result['task_model']}",
        (
            f"final test accuracy: {result['final_accuracy']:.1f}% "
            f"({result['correct']}/{result['test_examples']})"
        ),
    ]
    if result.get("validation_accuracy") is not None:
        lines.append(
            f"optimized validation accuracy: {result['validation_accuracy']:.1f}%"
        )
    if result.get("baseline_accuracy") is not None:
        lines.extend(
            [
                f"same-model baseline: {result['baseline_accuracy']:.1f}%",
                f"uplift: {result['uplift_points']:+.1f} points",
            ]
        )
    if result.get("accepted_trace_labels"):
        counts = result["accepted_trace_labels"]
        lines.append(
            f"accepted traces: human={counts['human']}, AI={counts['ai']}"
        )
    if result.get("optimization_cost_usd") is not None:
        lines.append(f"optimization cost: ${result['optimization_cost_usd']:.4f}")
    lines.extend(
        [
            f"optimization time: {result['optimization_seconds']:.1f}s",
            f"mean inference latency: {result['mean_latency_seconds']:.3f}s",
            f"p95 inference latency: {result['p95_latency_seconds']:.3f}s",
        ]
    )
    return "\n".join(lines)


def _openai_lm(model: str) -> dspy.LM:
    load_dotenv(REPO_ROOT / ".env")
    if not os.getenv("OPENAI_API_KEY"):
        raise EnvironmentError("Set OPENAI_API_KEY in the repository .env file")
    return SharedHistoryLM(model, cache=False, num_retries=1, timeout=120)


class SharedHistoryLM(dspy.LM):
    """Keep one accounting history when DSPy deep-copies candidate programs."""

    def __deepcopy__(self, memo: dict[int, Any]):
        del memo
        return self


def _finetune_kwargs(output_dir: Path) -> dict[str, Any]:
    from chapter06.apple_finetune import resolve_device

    device_preference = os.getenv("CHAPTER06_FINETUNE_DEVICE", "auto")
    return {
        "output_dir": str(output_dir),
        # DSPy's local trainer passes this value directly to ``model.to`` and
        # therefore cannot accept the inference wrapper's convenient "auto".
        "device": resolve_device(device_preference),
        "use_peft": True,
        "num_train_epochs": int(os.getenv("CHAPTER06_FINETUNE_EPOCHS", "10")),
        "per_device_train_batch_size": 1,
        "gradient_accumulation_steps": 4,
        "learning_rate": 2e-4,
        "max_seq_length": 768,
        "packing": False,
        "bf16": False,
    }


def _compile_prompt_optimizer(
    name: str,
    detector: AIDetector,
    trainset: list[dspy.Example],
    valset: list[dspy.Example],
    task_lm: dspy.LM,
    reflection_lm: dspy.LM,
    *,
    smoke: bool = False,
    artifact_dir: Path | None = None,
) -> dspy.Module:
    if name == "quickstart":
        return detector
    if name == "labeled-few-shot":
        return dspy.LabeledFewShot(k=4).compile(detector, trainset=trainset)
    if name == "bootstrap-few-shot":
        return dspy.BootstrapFewShot(
            metric=exact_match,
            max_bootstrapped_demos=2,
            max_labeled_demos=2,
            max_rounds=1,
            max_errors=1,
        ).compile(detector, trainset=trainset)
    if name == "bootstrap-random-search":
        return dspy.BootstrapFewShotWithRandomSearch(
            metric=exact_match,
            max_bootstrapped_demos=2,
            max_labeled_demos=2,
            num_candidate_programs=2 if smoke else 8,
            num_threads=1,
            max_errors=1,
        ).compile(detector, trainset=trainset, valset=valset)
    if name == "knn-few-shot":
        return dspy.KNNFewShot(
            k=4,
            trainset=trainset,
            vectorizer=dspy.Embedder(hashed_ngram_embeddings),
            metric=exact_match,
            max_bootstrapped_demos=0,
            max_labeled_demos=4,
        ).compile(detector)
    if name == "copro":
        return dspy.COPRO(
            prompt_model=reflection_lm,
            metric=exact_match,
            breadth=2 if smoke else 4,
            depth=1 if smoke else 2,
            init_temperature=1.0,
            track_stats=True,
        ).compile(
            detector,
            trainset=valset,
            eval_kwargs={
                "num_threads": 1,
                "display_progress": True,
                "display_table": False,
            },
        )
    if name == "miprov2":
        return dspy.MIPROv2(
            metric=exact_match,
            prompt_model=reflection_lm,
            task_model=task_lm,
            auto=None if smoke else "light",
            num_candidates=2 if smoke else None,
            max_bootstrapped_demos=2,
            max_labeled_demos=2,
            seed=42,
            log_dir=str(artifact_dir / "optimizer_logs") if artifact_dir else None,
        ).compile(
            detector,
            trainset=trainset,
            valset=valset,
            minibatch=True,
            requires_permission_to_run=False,
            num_trials=1 if smoke else None,
            minibatch_size=4 if smoke else 35,
        )
    if name == "gepa":
        return dspy.GEPA(
            metric=feedback_metric,
            max_full_evals=1 if smoke else 6,
            reflection_minibatch_size=3,
            reflection_lm=reflection_lm,
            num_threads=1,
            use_merge=False,
            track_best_outputs=True,
            seed=42,
            log_dir=str(artifact_dir / "optimizer_logs") if artifact_dir else None,
        ).compile(detector, trainset=trainset, valset=valset)
    if name == "simba":
        return dspy.SIMBA(
            metric=exact_match,
            bsize=4 if smoke else 8,
            num_candidates=2 if smoke else 4,
            max_steps=1 if smoke else 6,
            max_demos=2,
            prompt_model=reflection_lm,
        ).compile(detector, trainset=trainset, seed=42)
    if name == "ensemble":
        labeled = dspy.LabeledFewShot(k=4).compile(
            detector.deepcopy(), trainset=trainset
        )
        bootstrapped = dspy.BootstrapFewShot(
            metric=exact_match,
            max_bootstrapped_demos=2,
            max_labeled_demos=2,
            max_rounds=1,
            max_errors=1,
        ).compile(detector.deepcopy(), trainset=trainset)
        searched = dspy.BootstrapFewShotWithRandomSearch(
            metric=exact_match,
            max_bootstrapped_demos=2,
            max_labeled_demos=2,
            num_candidate_programs=2 if smoke else 8,
            num_threads=1,
            max_errors=1,
        ).compile(detector.deepcopy(), trainset=trainset, valset=valset)
        return dspy.Ensemble(reduce_fn=boolean_majority).compile(
            [labeled, bootstrapped, searched]
        )
    raise ValueError(f"unknown prompt optimizer {name!r}")


def run_optimizer(
    optimizer: str,
    *,
    splits: dict[str, list[dspy.Example]] | None = None,
    include_baseline: bool = False,
    task_model: str = "openai/gpt-5.6-luna",
    reflection_model: str = "openai/gpt-5.6-sol",
    local_model: str = "Qwen/Qwen2.5-0.5B-Instruct",
    output_dir: Path | None = None,
    artifact_dir: Path | None = None,
    mode: str = "full",
) -> OptimizerRun:
    """Compile one optimizer and evaluate it on the shared untouched test split."""

    if optimizer not in OPTIMIZERS:
        raise ValueError(f"unknown optimizer {optimizer!r}")
    if mode not in {"smoke", "full"}:
        raise ValueError("mode must be 'smoke' or 'full'")
    smoke = mode == "smoke"
    splits = splits or load_frozen_examples()
    trainset = splits["train"][:8] if smoke else splits["train"]
    valset = splits["validation"][:4] if smoke else splits["validation"]
    testset = [] if smoke else splits["test"]
    accepted_counts: dict[str, int] | None = None
    actual_output_dir: Path | None = None

    if optimizer in WEIGHT_OPTIMIZERS:
        from chapter06.apple_finetune import TransformersLocalLM, make_model_spec

        task_lm = TransformersLocalLM(
            model=make_model_spec(local_model),
            device=os.getenv("CHAPTER06_FINETUNE_DEVICE", "auto"),
            max_context_tokens=1024,
            max_tokens=96,
            cache=False,
        )
        # A stronger remote teacher prevents the local 0.5B student from
        # bootstrapping only its own majority-class mistakes.
        teacher_lm = _openai_lm(reflection_model)
        teacher = AIDetector()
        teacher.set_lm(teacher_lm)
        reflection_lm = teacher_lm
        detector = AIDetector()
        detector.set_lm(task_lm)
        dspy.configure(lm=task_lm)
        actual_output_dir = output_dir or Path(
            tempfile.mkdtemp(prefix=f"chapter06-{optimizer}-")
        )
    else:
        task_lm = _openai_lm(task_model)
        reflection_lm = _openai_lm(reflection_model)
        teacher = None
        detector = AIDetector()
        detector.set_lm(task_lm)
        dspy.configure(lm=task_lm)

    baseline_examples = valset if smoke else testset
    baseline = evaluate(detector, baseline_examples) if include_baseline else None
    cost_before_compile = float(_combined_usage(task_lm, reflection_lm)["cost_usd"])
    started = time.monotonic()
    if optimizer in PROMPT_OPTIMIZERS:
        program = _compile_prompt_optimizer(
            optimizer,
            detector,
            trainset,
            valset,
            task_lm,
            reflection_lm,
            smoke=smoke,
            artifact_dir=artifact_dir,
        )
    elif optimizer == "bootstrap-finetune":
        finetuner = BalancedBootstrapFinetune(
            metric=exact_match,
            train_kwargs=_finetune_kwargs(actual_output_dir),
            exclude_demos=True,
            num_threads=1,
            min_examples_per_class=2,
        )
        program = finetuner.compile(detector, trainset=trainset, teacher=teacher)
        accepted_counts = finetuner.accepted_label_counts
    else:
        max_errors = len(trainset) + len(valset)
        finetuner = BalancedBootstrapFinetune(
            metric=exact_match,
            train_kwargs=_finetune_kwargs(actual_output_dir),
            exclude_demos=False,
            num_threads=1,
            min_examples_per_class=2,
        )
        prompt_optimizer = dspy.BootstrapFewShotWithRandomSearch(
            metric=exact_match,
            max_bootstrapped_demos=2,
            max_labeled_demos=2,
            num_candidate_programs=2 if smoke else 4,
            num_threads=1,
            max_errors=max_errors,
        )
        program = dspy.BetterTogether(
            metric=exact_match, p=prompt_optimizer, w=finetuner
        ).compile(
            detector,
            trainset=trainset,
            teacher=teacher,
            valset=valset,
            num_threads=1,
            max_errors=max_errors,
            seed=42,
            strategy="p -> w",
            # BetterTogether normalizes its teacher to a list for weight
            # optimizers, but BootstrapRS expects one module. Override only
            # the prompt step with the original teacher module.
            optimizer_compile_args={"p": {"teacher": teacher}},
        )
        if getattr(program, "flag_compilation_error_occurred", False):
            raise RuntimeError("BetterTogether stopped before completing p -> w")
        accepted_counts = finetuner.accepted_label_counts or None
    optimization_seconds = time.monotonic() - started
    cost_after_compile = float(_combined_usage(task_lm, reflection_lm)["cost_usd"])
    # Prompt optimizers often return a deep-copied program. Reattach the
    # canonical task LM so standardized validation/test calls land in the same
    # cost ledger. Weight optimizers must retain the newly fine-tuned LM.
    if optimizer in PROMPT_OPTIMIZERS:
        program.set_lm(task_lm)
    validation = evaluate(program, valset)
    final = evaluate(program, testset) if testset else None
    usage = _combined_usage(task_lm, reflection_lm)
    final_cost = float(usage["cost_usd"])
    return OptimizerRun(
        optimizer=optimizer,
        task_model=local_model if optimizer in WEIGHT_OPTIMIZERS else task_model,
        final=final,
        validation=validation,
        program=program,
        optimization_seconds=optimization_seconds,
        baseline=baseline,
        accepted_trace_labels=accepted_counts,
        output_dir=str(actual_output_dir) if actual_output_dir else None,
        mode=mode,
        optimization_cost_usd=max(0.0, cost_after_compile - cost_before_compile),
        evaluation_cost_usd=max(0.0, final_cost - cost_after_compile),
        usage=usage,
    )
