from __future__ import annotations

import json
import unittest
from unittest.mock import patch

from chapter06.build_expanded_comparison import _build_run_ledger, _run_row
from chapter06.build_optimizer_notebooks import CHAPTER_DIR, NOTEBOOKS
from chapter06.notebook_support import optimizer_row, verify_prompt_artifact
from chapter06.optimizer_runtime import AIDetector, _compile_prompt_optimizer
from chapter06.validate_notebooks import validate_notebook


class PublishedNotebookTest(unittest.TestCase):
    def test_manuscript_canonical_copro_and_simba_artifacts(self) -> None:
        copro = optimizer_row("copro")
        self.assertEqual(copro["locked_test_accuracy_pct"], 56.25)
        self.assertEqual(copro["optimization_cost_usd"], 0.81558)
        self.assertAlmostEqual(
            copro["optimization_time_seconds"], 1155.7725224589813
        )
        self.assertEqual(
            copro["result_artifact"],
            "chapter06/results/expanded_notebooks/copro/"
            "rerun-20260719-124750/result.json",
        )

        expected_copro_instruction = (
            "Analyze the supplied passage for linguistic, stylistic, and structural "
            "signals associated with AI-generated versus human-written text. Consider "
            "factors such as formulaic phrasing, repetition, coherence patterns, "
            "specificity, natural variation, and errors, while avoiding reliance on "
            "topic or unsupported assumptions. Make a forced-choice classification "
            "based only on the passage. Output exactly one label: `AI-generated` or "
            "`Human-written`."
        )
        copro_prompt = json.loads(
            (CHAPTER_DIR.parent / copro["prompt_artifact"]).read_text(encoding="utf-8")
        )
        self.assertEqual(
            copro_prompt["predictors"]["detect.predict"]["instructions"],
            expected_copro_instruction,
        )

        simba = optimizer_row("simba")
        simba_prompt = json.loads(
            (CHAPTER_DIR.parent / simba["prompt_artifact"]).read_text(encoding="utf-8")
        )["predictors"]["detect.predict"]
        self.assertEqual(
            simba_prompt["instructions"],
            "Decide whether the supplied passage was generated by an AI.",
        )
        self.assertEqual(simba_prompt["demos"], [])

        ledger = json.loads(
            (
                CHAPTER_DIR
                / "results"
                / "expanded_notebooks"
                / "run_ledger.json"
            ).read_text(encoding="utf-8")
        )
        canonical_copro_runs = [
            run
            for run in ledger["runs"]
            if run.get("optimizer") == "copro"
            and run.get("status") == "completed"
            and run.get("manuscript_canonical")
        ]
        self.assertEqual(len(canonical_copro_runs), 1)
        self.assertEqual(
            canonical_copro_runs[0]["result_artifact"], copro["result_artifact"]
        )

        miprov2_rerun = next(
            run
            for run in ledger["runs"]
            if run.get("optimizer") == "miprov2"
            and run.get("run_name") == "rerun-20260719-124750"
        )
        self.assertEqual(miprov2_rerun["optimization_cost_status"], "recorded")
        self.assertEqual(miprov2_rerun["evaluation_cost_status"], "recorded")
        self.assertAlmostEqual(miprov2_rerun["evaluation_cost_usd"], 0.213767)

        self.assertFalse(
            (CHAPTER_DIR / "results" / "final_prompts").exists()
        )
        self.assertFalse(
            (CHAPTER_DIR / "results" / "benchmark_summary.json").exists()
        )

    def test_comparison_builder_selects_the_manuscript_canonical_copro_run(
        self,
    ) -> None:
        copro = _run_row(
            "copro",
            canonical_baseline=53.75,
            baseline_predictions=None,
        )
        self.assertEqual(copro["manuscript_run_name"], "rerun-20260719-124750")
        self.assertEqual(copro["locked_test_accuracy_pct"], 56.25)
        self.assertEqual(copro["optimization_cost_status"], "recorded")
        self.assertEqual(copro["evaluation_cost_status"], "recorded")

        copro_runs = [
            run
            for run in _build_run_ledger()["runs"]
            if run.get("optimizer") == "copro" and run.get("status") == "completed"
        ]
        canonical_runs = [run for run in copro_runs if run["manuscript_canonical"]]
        self.assertEqual(
            [run["run_name"] for run in canonical_runs],
            ["rerun-20260719-124750"],
        )
        self.assertEqual(canonical_runs[0]["optimization_cost_status"], "recorded")
        historical_full = next(
            run for run in copro_runs if run["run_name"] == "full"
        )
        self.assertFalse(historical_full["manuscript_canonical"])
        self.assertEqual(
            historical_full["optimization_cost_status"], "partial_lower_bound"
        )

    def test_every_optimizer_notebook_is_executed_and_educational(self) -> None:
        for filename, spec in NOTEBOOKS.items():
            with self.subTest(filename=filename):
                self.assertEqual(
                    validate_notebook(
                        CHAPTER_DIR / filename,
                        spec["optimizer"],
                        require_executed=True,
                    ),
                    [],
                )

    def test_frozen_program_prompt_state_matches_extracted_prompt(self) -> None:
        for spec in NOTEBOOKS.values():
            optimizer = spec["optimizer"]
            row = optimizer_row(optimizer)
            check = verify_prompt_artifact(optimizer)
            with self.subTest(optimizer=optimizer):
                self.assertEqual(row["status"], "completed")
                self.assertTrue(check["checked"])
                self.assertTrue(check["prompt_state_equal"])

    def test_every_notebook_loads_the_shared_split_and_can_run_live(self) -> None:
        for filename in NOTEBOOKS:
            source = (CHAPTER_DIR / filename).read_text(encoding="utf-8")
            with self.subTest(filename=filename):
                self.assertIn("load_frozen_examples", source)
                self.assertIn("run_optimizer", source)
                self.assertIn("CHAPTER06_RUN_LIVE", source)

    def test_gepa_uses_the_standard_light_configuration_and_protocol(self) -> None:
        spec = NOTEBOOKS["gepa.ipynb"]
        self.assertIn("auto='light'", spec["compile"])
        self.assertIn("candidate_selection_strategy='pareto'", spec["compile"])
        self.assertIn("use_merge=False", spec["compile"])

        row = optimizer_row("gepa")
        self.assertEqual(
            row["evaluation_protocol"],
            "one fresh uncached validation pass, then one locked-test pass",
        )
        self.assertEqual(row["baseline_accuracy_pct"], 53.75)
        self.assertEqual(row["locked_test_accuracy_pct"], 80.0)

    def test_live_gepa_runner_matches_the_published_configuration(self) -> None:
        class FakeGEPA:
            kwargs: dict[str, object] = {}

            def __init__(self, **kwargs: object) -> None:
                type(self).kwargs = kwargs

            def compile(self, student: AIDetector, **kwargs: object) -> AIDetector:
                return student

        with patch("chapter06.optimizer_runtime.dspy.GEPA", FakeGEPA):
            _compile_prompt_optimizer(
                "gepa",
                AIDetector(),
                [],
                [],
                object(),
                object(),
                smoke=False,
            )

        self.assertEqual(FakeGEPA.kwargs["auto"], "light")
        self.assertNotIn("max_full_evals", FakeGEPA.kwargs)
        self.assertEqual(FakeGEPA.kwargs["candidate_selection_strategy"], "pareto")
        self.assertIs(FakeGEPA.kwargs["use_merge"], False)


if __name__ == "__main__":
    unittest.main()
