#!/usr/bin/env python3
"""Collect the "Book vs. notebook" notes from the notebooks into BOOK_NOTES.md.

The notebooks reproduce the printed listings of the book. Where a notebook adds
to a listing or shows a runnable version next to it, a markdown cell explains
the difference in a paragraph that starts with **Book vs. notebook:**. This
script gathers those paragraphs, grouped by chapter and notebook.

Run it from the repository root after adding or editing a note:

    uv run python scripts/build_book_notes.py

Use --check to verify that BOOK_NOTES.md is up to date without rewriting it.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "BOOK_NOTES.md"
CHAPTER_TITLES = {
    1: "Introduction to Context Engineering",
    2: "Introduction to DSPy",
    3: "DSPy in Eight Steps",
    4: "Strategies for Collecting Datasets",
    5: "Evaluation Metrics",
    6: "Deep Dive into Prompt Optimizers",
    7: "Custom Modules, Types, and Adapters",
    8: "Building AI Agents",
    9: "Real-World Use Cases",
    10: "Putting DSPy into Production",
    11: "Optimizing Coding Agents with DSPy",
}
NOTE_START = re.compile(r"^\s*(>\s*)?\*\*Book vs\.? notebook:?\*\*:?\s*", re.IGNORECASE)
HEADER = """\
# Notes on differences from the printed listings

The notebooks in this repository reproduce the code listings of *Context Engineering with DSPy* as they are printed.
Some printed listings are abbreviated, use names the chapter does not define, or depend on a service, a key, or a
budget that a notebook should not assume. In those places the notebook keeps the listing as printed and explains what
it adds or does differently in a **Book vs. notebook** note. This page collects those notes so you can see them in one
place.

Each note is quoted from its notebook, so "the next cell" or "the cell below" means the cell that follows the note
there. Page numbers refer to the print edition.

This page is generated by `scripts/build_book_notes.py`. Edit the note in the notebook, then run the script again.
"""


def notes_in(notebook_path: Path) -> list[str]:
    """Return the text of every "Book vs. notebook" paragraph in one notebook."""
    notebook = json.loads(notebook_path.read_text(encoding="utf-8"))
    notes: list[str] = []
    for cell in notebook["cells"]:
        if cell["cell_type"] != "markdown":
            continue
        source = "".join(cell["source"])
        for paragraph in re.split(r"\n\s*\n", source):
            if not NOTE_START.match(paragraph.strip()):
                continue
            lines = [re.sub(r"^\s*>\s?", "", line).strip() for line in paragraph.strip().splitlines()]
            text = NOTE_START.sub("", " ".join(lines), count=1).strip()
            notes.append(text)
    return notes


def build() -> str:
    """Return the full text of BOOK_NOTES.md."""
    parts = [HEADER]
    for chapter, title in CHAPTER_TITLES.items():
        folder = f"chapter{chapter:02d}"
        sections: list[str] = []
        for notebook_path in sorted((REPO_ROOT / folder).glob("*.ipynb")):
            notes = notes_in(notebook_path)
            if not notes:
                continue
            link = f"{folder}/{notebook_path.name}"
            sections.append(f"### [`{link}`]({link})\n\n" + "\n".join(f"- {note}" for note in notes) + "\n")
        if sections:
            parts.append(f"## Chapter {chapter}: {title}\n")
            parts.extend(sections)
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="exit with status 1 if BOOK_NOTES.md is out of date")
    args = parser.parse_args()
    text = build()
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        if current != text:
            print("BOOK_NOTES.md is out of date. Run: uv run python scripts/build_book_notes.py")
            return 1
        print("BOOK_NOTES.md is up to date.")
        return 0
    OUTPUT_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({text.count(chr(10) + '- ')} notes).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
